### ISSUE TITLE
-[BFTask waitUntilFinished] does not account for spurious thread wakeup

### ISSUE THREAD

**Issue by toddreed** [BoltsFramework/Bolts-ObjC#134]
See https://en.wikipedia.org/wiki/Spurious_wakeup for a description of "spurious wakeup". This seems to apply to `NSCondition`, as Apple's documentation (Threading Programming Guide) states:

> Due to the subtleties involved in implementing operating systems, condition locks are permitted to return with spurious success even if they were not actually signaled by your code. To avoid problems caused by these spurious signals, you should always use a predicate in conjunction with your condition lock.

(The reference documentation for `NSCondition` also touches on this topic.)

I think something like this may be more correct:

```objc
- (void)waitUntilFinished {
    if ([NSThread isMainThread]) {
        [self warnOperationOnMainThread];
    }

    @synchronized (self.lock) {
        if (self.completed) {
            return;
        }
        [self.condition lock];
    }
    while (YES) {
        [self.condition wait];

        @synchronized (self.lock) {
            if (self.completed)
                break;
        }
    }

    [self.condition unlock];
}
```

Alternately, using `dispatch_semaphore_t` may provided a simpler implementation.

(Note that I have not actually observed a spurious wakeup. I don't know if this is a possibility on iOS.)

**Comment by nlutsenko** [comment]
Thanks for raising this! It can indeed happen!
Since iOS is using pthreads or mach semaphores (`mach/semaphore.h` aka `semaphore_wait()`) behind the scenes in NSCondition - I think it's quite possible to observe spurious wakeup.
If we would use dispatch_semaphore - that one has logic around it to specifically address this problem [source](http://www.opensource.apple.com/source/libdispatch/libdispatch-84.5/src/semaphore.c).

Looking forward to see a Pull Request, or I am going to get to it at some point before 1.2.2 cut.
