### ISSUE TITLE
Provide a result for taskForCompletionOfAllTasks

### ISSUE THREAD

**Issue by jtbthethird** [BoltsFramework/Bolts-ObjC#23]
I want to do multiple asynchronous tasks in parallel, each of which returns a value, and then when all have completed, get an array of those results.

As of now, taskForCompletionOfAllTasks just returns a result of nil.

**Comment by gazialankus** [comment]
In a task chain, the task above has a task array in its closure. The task below needs to get the results of the task array from task.result, but it can't, because the task array is in the scope of the above closure. 

In a task chain like this, we don't have access to the `BFTask`s that we waited on. 

Or, you may want to get the task that taskForCompletionOfAllTasks gives, and send it somewhere else in your project. Sending the task array along with it is not a good solution. It's a shame that this issue is closed.

**Comment by nlutsenko** [comment]
@gazialankus 
![666ec8587d11b175c1b44dbcfec1df4bcd4a0a455737ca75eb3939a766fc0d31](https://cloud.githubusercontent.com/assets/606991/15976898/5ee5384e-2f0a-11e6-9f64-fa036c0d521e.jpg)

**Comment by nlutsenko** [comment]
This issue is probably actually resolved, since we have `taskForCompletionAllTasksWithResults:` now, which does exactly what you are describing - provides an array of results on successful completion of all tasks. [Header reference here](https://github.com/BoltsFramework/Bolts-ObjC/blob/master/Bolts/Common/BFTask.h#L104)

**Comment by gazialankus** [comment]
OOH my bad! Sorry about that, and thank you for this awesome piece of software your highness :)
