### ISSUE TITLE
Opt out exceptions

### ISSUE THREAD

**Issue by hovox** [BoltsFramework/Bolts-ObjC#250]
Exception handling is not recommended in Objective-C, and by default it's turned off, so in case of exceptions there will be memory leaks.

Can we have a way to opt out exceptions ? For example with some macro, if macro is defined, then skip `@try/@catch` . Thanks in advance.

**Comment by nlutsenko** [comment]
This actually is a wonderful idea.
Exceptions are pretty bad anyway and I do agree that it's better to crash and get a stack trace than to try/catch and fail a network request and be in an unknown state.

We can do in a macro way, but then you wouldn't be able to opt-out of this in the case of dynamic frameworks, which probably is a good thing to cover.

Since we have `Bolts` as a source file - I think adding 2 extra C functions (getter and setter) would work probably best.

**Comment by hovox** [comment]
Agree, that would be great.
