### ISSUE TITLE
Files not found after Parse + Facebook pod update

### ISSUE THREAD

**Issue by localsDeveloper** [BoltsFramework/Bolts-ObjC#278]

**Comment by sash83** [comment]
Several Bolts files are not found (e.g. BFAppLink_Internal.h).
Does anyone know the cause and how to fix it?

Also, is there a way to replace the Bolts framework with Bolts-Swift when using Parse and ParseFacebookUtils? Because Bolts framework is integrated automatically.

**Comment by nlutsenko** [comment]
Hey guys, please create new concrete issues with error code, repro project and as much information that you can provide about the issues that you are experiencing.
Overall, if you integrate Bolts into any pod - everything works fine and is tested on every commit, meaning that there is something specific either about your specific setup or might be even a stale cache issues.

Since this sounds like a Parse SDK specific issue, I would recommend reporting the issue over there as well.

> Also, is there a way to replace the Bolts framework with Bolts-Swift when using Parse and ParseFacebookUtils?

Not as of right now, no, but there have been few requests about converting one into another (ObjC to Swift). If you have a concrete implementation - please contribute it to Bolts-Swift repo, and I'll gladly merge it in.
